### ISSUE TITLE
Conflict with last function in xts package

### ISSUE THREAD

**Issue by Nygdat** [mdancho84/tidyquant#14] opened 2017-02-12 22:24 UTC
When the tidyquant package is loaded there is a conflict with "last" function in xts.

When I do last(prices, 1) to get last row of xts object, I get the following error:

Error in x[[order(order_by)[n]]] : subscript out of bounds

**Comment by mdancho84** [comment] 2017-02-12 22:47
@Nygdat 

We will look into this right away, but first if you can do me a favor and provide a reproducible code snippet that results in the error you describe above. We need this to recreate the issue. 

Thanks, Matt

**Comment by Nygdat** [comment] 2017-02-12 23:00
Hi,
Thanks for looking into this. Great package. Thanks for the work.
regards

This should reproduce the error.

library(xts)
prices <- c(1,2,3)
last(prices, 1)
output --> [3]

library(tidyquant)
last(prices, 1)
Error in x[[order(order_by)[n]]] : subscript out of bounds

2017-02-12 23:47 GMT+01:00 Matt Dancho <notifications@github.com>:

**Comment by mdancho84** [comment] 2017-02-12 23:33
@Nygdat 

Thanks. That reproduces the error alright. While this is an inconvenience for your situation, it's not technically a bug with `tidyquant`. The output when the `tidyquant` package is loaded shows the potential conflicts (see output at end). Your error arises because of `dplyr` superceding `xts`. There's a conflict with functions with the same name: `dplyr::last()` supercedes `xts::last()`.  

You have a few options to resolve this.
1. Specify which package to pull the function from. `xts::last()`
2. Use `last()` from `dplyr`. The downside is you only get the last value (i.e. you can't specify more than the last value to retrieve).
3. Use `tail()` which is essentially the same as `xts::last()`. 

```
> library(tidyquant)
> prices <- c(1,2,3)
> last(prices, 1)
Error in x[[order(order_by)[n]]] : subscript out of bounds
> 
> # Option 1: Specify xts::last()
> xts::last(prices, 1)
[1] 3
> 
> # Option 2: Use dplyr::last()
> last(prices)
[1] 3
> 
> # Option 3: Use tail()
> tail(prices, 1)
[1] 3
> 
```

**Output showing potential conflicts:**
```
> library(tidyquant)
Loading required package: lubridate

Attaching package: ‘lubridate’

The following object is masked from ‘package:base’:

    date

Loading required package: PerformanceAnalytics

Package PerformanceAnalytics (1.4.3541) loaded.
Copyright (c) 2004-2014 Peter Carl and Brian G. Peterson, GPL-2 | GPL-3
http://r-forge.r-project.org/projects/returnanalytics/


Attaching package: ‘PerformanceAnalytics’

The following object is masked from ‘package:graphics’:

    legend

Loading required package: quantmod
Loading required package: TTR
Version 0.4-0 included new data defaults. See ?getSymbols.
Loading required package: tidyverse
Loading tidyverse: ggplot2
Loading tidyverse: tibble
Loading tidyverse: tidyr
Loading tidyverse: readr
Loading tidyverse: purrr
Loading tidyverse: dplyr
Conflicts with tidy packages ------------------------------------------------------------------
as.difftime(): lubridate, base
date():        lubridate, base
filter():      dplyr, stats
first():       dplyr, xts
intersect():   lubridate, base
lag():         dplyr, stats
last():        dplyr, xts
setdiff():     lubridate, base
union():       lubridate, base

Attaching package: ‘tidyquant’

The following object is masked from ‘package:tibble’:

    as_tibble
```

**Comment by Nygdat** [comment] 2017-02-13 05:49
Thanks! This function call is part from the Systematic Investor package.

I cannot change it because it is Read-Only in RStudio. Maybe a simple
question, but
do you know how I can change Read-Only status in RStudio?

Or is it not possible to change the original code in packages?

regards,
Lars

2017-02-13 0:33 GMT+01:00 Matt Dancho <notifications@github.com>:

**Comment by Nygdat** [comment] 2017-02-13 08:45
Hi Matt,
I just found a solution to this with : last <- xts::last

If I put this line in my script it uses last function from xts package.

Best regards,
Lars Nygaard

2017-02-13 6:49 GMT+01:00 Lars Nygaard <lrs.ngrd@gmail.com>:

**Comment by mdancho84** [comment] 2017-02-13 10:47
Lars,

Nice hack! `last <- xts::last` is a good solution to this problem, and I'm glad you've posted so future us will remember. 👍 

Also, typically in packages is best practice to bind the function to the library from which it comes. I don't have much experience with the Systematic Investor package, but within it the function must not be bound to the library. This is not a major issues unless there are conflicts. 

I'm going to close this one out. Thanks again.

-Matt

**Closed by mdancho84** 2017-02-13 10:47 UTC

**Comment by joshuaulrich** [comment] 2017-03-14 12:27
> 3. Use tail() which is essentially the same as xts::last().

`tail()` is only "essentially the same" as `xts::last()` if you don't use any of the advanced subsetting features of `xts::last()` (i.e. you only specify the number of observations to return by using an integer).

```r
library(xts)
data(sample_matrix)
x <- as.xts(sample_matrix)
# essentially the same as tail()
last(x, 5)
# tail() can't do this
last(x, "1 week")
```

----

> I just found a solution to this with : last <- xts::last
> 
> If I put this line in my script it uses last function from xts package.

Be forewarned that you might need to do something similar for `lag()`.  `dplyr::lag()` masks `stats::lag()` (a generic), which prevents method dispatch.  So if you call `lag(x)` on an xts object, you may get an error.

```r
library(xts)
data(sample_matrix)
x <- as.xts(sample_matrix)
head(merge(x, lag(x))) # works
library(dplyr)
head(merge(x, lag(x))) # Error in `[.xts`(x, seq_len(xlen - n)) : subscript out of bounds
```

**Comment by mdancho84** [comment] 2017-03-14 12:47
Josh,
Thanks for the comments. I agree with both points. The `last()` function does have some additional functionality for subsetting which is one of the core benefits of the xts system. I don't mean to understate this. Rather, I was trying to come up with some alternatives.

Also, I see what you mean with the `dplyr::lag()` versus `stats::lag()`. This has some potential to create issues due to the conflicting names. Clearly this issue resulted from the conflict. I'll be on the lookout for more issues... there's always something.
-Matt

**Comment by wadexyz** [comment] 2019-03-04 02:57
Ugh, I'm very happy these threads exist, but I can't imagine this is considered a good situation by any parties involved.    I get there's a "warning" in the console, but the whole thing still seems "off".
