### ISSUE TITLE
Yahoo data source for dividends sometimes faulty

### ISSUE THREAD

**Issue by robby81** [mdancho84/tidyquant#18] opened 2017-02-23 08:18 UTC
I have two ETFs in my portfolio for which yahoo has no dividend information and thus the adjusted price column is incorrect. If you do not figure out that and you work with the adjusted prices your analysis is not correct.
Maybe there is a possibility to check for it and give a warning?

**Comment by robby81** [comment] 2017-02-24 08:28
I am trying to calculate the adjusted price by myself, but it does not match the yahoo adhusted prices. Do you have an idea, what I am doing wrong?

JNK_ori <- tq_get("JNK", get = "stock.prices", from = from, to = today()) %>% mutate(symbol = rep("JNK_yahoo", n()))
JNK_divs <- tq_get("JNK", get = "dividends", from = from, to = today()) %>% mutate(symbol = rep("JNK_yahoo", n()))
test <- JNK_ori %>% left_join(JNK_divs)
test$dividends[is.na(test$dividends)] <- 0
JNK_new <- test %>% mutate(cumdivs = cumsum(dividends)[length(dividends):1], adjusted_new = close/(1-(cumdivs/clos)) %>% select(symbol:volume, adjusted_new) %>% rename(adjusted=adjusted_new)
JNK_new$symbol[JNK_new$symbol=="JNK"] <- "JNK_new"
JNK <- bind_rows(JNK_ori, JNK_new)
ggplot(JNK, aes(x=date, y=adjusted)) + geom_line(aes(color=symbol))

Such a function would also be quite helpful, I guess.

**Comment by DavisVaughan** [comment] 2017-02-24 20:10
Hi Robby, 
Two things:

1) Could you please provide us with the two ETFs without dividend info? We can look into it with a reproducible example. 

2) For your second point about calculating the adjusted closing prices, this link may be helpful. http://marubozu.blogspot.com/2006/09/how-yahoo-calculates-adjusted-closing.html Using it, and solving for `A0` (today's adjusted price) in their equation, I was able to recreate the adjusted closing prices for JNK that Yahoo produces. Below is my quick and dirty work for that. Note that you need yesterday's adjusted close price to do this.

``` r
suppressPackageStartupMessages(library(tidyquant))

# Start date
from <- "2005-01-01"

# Historical prices 
JNK_ori <- tq_get("JNK", get = "stock.prices", from = from, to = today()) %>% 
  mutate(symbol = rep("JNK_yahoo", n())) %>% 
  select(symbol, everything())

# Dividends
JNK_divs <- tq_get("JNK", get = "dividends", from = from, to = today()) %>% 
  mutate(symbol = rep("JNK_yahoo", n())) %>% 
  select(symbol, everything())

# Join and clean
test <- JNK_ori %>% left_join(JNK_divs)
#> Joining, by = c("symbol", "date")
test$dividends[is.na(test$dividends)] <- 0

# Calculate adjusted stock price
# An ugly loop, could probably be cleaned up
test$adjusted_calc <- 0
for (i in 1:(nrow(test)-1)){
  test$adjusted_calc[i+1] <- test$adjusted[i] / (1 + (test$close[i] - test$close[i+1] - test$dividends[i+1]) / test$close[i+1])
}
```

**Comment by robby81** [comment] 2017-02-24 23:28
Thank you for the code example for the adjusted price calculation. Will try it here probably tomorrow. The two ETFs without dividend info have the symbols SPYV.DE and IUS7.DE. Both are distributing and I already got the dividend history from ishares and spdr websites.

**Comment by mdancho84** [comment] 2017-03-06 18:27
@robby81 
Unfortunately, this is a problem with yahoo data and because of this we'd be creating a work around to try and correct the anomaly. I don't think this is good practice. I hate to say this, but I think this is best handled on a per issue basis by the user. These are the dangers with free data. However, thank you for bringing this to our attention so we are aware of the potential issue and can instruct others to watch out.
-Matt

**Closed by mdancho84** 2017-03-06 18:27 UTC
