### ISSUE TITLE
Error : tidyquant doesn't support Linux OS

### ISSUE THREAD

**Issue by englianhu** [mdancho84/tidyquant#10] opened 2017-02-01 12:59 UTC
I tried to deploy shinyApp and noticed the `tidyquant` unable install due to no url...
![](https://cloud.githubusercontent.com/assets/7227582/22507069/062eafba-e8c7-11e6-95fa-48247ec1f4b5.png)

After that I check with the official R website and only know the package [*tidyquant*: Tidy Quantitative Financial Analysis](https://cran.r-project.org/package=tidyquant) doesn't support Linux OS while Linux is an OS suite for programmers.

**Comment by mdancho84** [comment] 2017-02-01 13:48
Thanks @englianhu. We are looking into this and will get back to you ASAP.

**Comment by mdancho84** [comment] 2017-02-01 14:13
@englianhu 
@DavisVaughan and I are investigating, but we do not have enough information to reproduce the error. I'd like you try two things:

1. Run your application using the latest development version. You can install it with `devtools`. And note that there are several changes from the NEWS.md file that may be of interest.

2. If (1) does not work, we will need to access a copy of your application that is causing the error. The easiest way is to send a link to a github repo. We will attempt to reproduce the problem and debug.

**Comment by DavisVaughan** [comment] 2017-02-01 21:38
@englianhu 

I have forked, cloned, and successfully deployed your application onto shiny.io (it is very cool, great job).

https://davisvaughan.shinyapps.io/binarycom-interview-question/

 I was able to deploy it with both `tidyquant 0.3.0.9050` from GitHub, and with `tidyquant 0.3.0` from CRAN. Here is what the output of `rsconnect::deployApp()` gave me when I built under 0.3.0:
![screen shot 2017-02-01 at 4 16 58 pm](https://cloud.githubusercontent.com/assets/19150088/22527236/68e6e4fe-e89c-11e6-82c9-3f81b211931d.png)

The warning did not prevent the build from working.

What is the code that you ran that gave you those errors? We would love to help you if you can provide us with some more information!

Also, as @mdancho84 said, try updating to the GitHub version and see if that helps.

Lastly, where is the code that actually uses `tidyquant`? I briefly searched through the shiny app but could not find anything that used any of our functions.

Thanks!

**Comment by mdancho84** [comment] 2017-02-04 21:02
@englianhu 

We are closing this comment out. Davis was able to successfully deploy your Shiny application with the tidyquant dependency. Further the tidyquant builds have all passed Travis CI using unbuntu. We believe the issue is unrelated to tidyquant

**Closed by mdancho84** 2017-02-04 21:02 UTC
